app:
  name: poc
  description: ${app.name} is poc project to verify spring boot

yu:
  port: 1001
  server: host-address
  roles:
    - admin
    - user

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: DEBUG

spring:
  datasource:
    url: jdbc:h2:mem:dev;MODE=MySql;DB_CLOSE_DELAY=-1