app:
  name: poc
  description: ${app.name} is poc project to verify spring boot


jdbc:
  url: jdbc:log4jdbc:h2:mem:test;MODE=MySql;DB_CLOSE_DELAY=-1

yu:
  port: 1001
  server: host-address
  roles:
    - admin
    - user

logging:
  level:
    root: WARN
    org.springframework.web: DEBUG
    org.hibernate: DEBUG